version: '3'

services:
  #PHP Service
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: php
    container_name: php
    restart: "no"
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: "no"
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  #MySQL Service
  mysql:
    image: mysql
    container_name: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: "no"
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    volumes:
      - ./docker/logs/sessions:/sessions
    networks:
      - app-network
  nodejs:
    image: node:12
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    expose:
      - 8083
    volumes:
      - ./:/home/node/app
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
